### ISSUE TITLE
Using it on Windows Server 2008R2

### ISSUE THREAD

**Issue by MontyGvMC** [PeterKottas/DotNetCore.WindowsService#12]
Thank you for your hint on [StackOverflow](http://stackoverflow.com/questions/41014513/windows-service-with-net-core/42377351#42377351).

I used your library and it works like charm. Thank you for your great work.

Unfortunatly I tried to run it on Windows Server 2008 R2 too and there it seems the service does not start/run.

The service gets installed and started but it seem it is exiting the Main method immediatly without starting/running the service.

Do you have information if it should run on R2 too?

**Comment by PeterKottas** [comment]
Hi there glad you find it useful :) As far as I know it should work right of the box. So let's discuss some details. 
1. How do you run the service? With dotnet nameOfDll.dll action:install or does your pipeline produce an executable and you run it directly? Whatever option you use currently, I would start by using the other just to double check. 
2. What version of this lib are you using?
3. What version of dotnet sdk do you have on the dev/build machine and do you have the same one on the 2008 r2 server? 
4. I think those 3 are enough for now :D

**Comment by MontyGvMC** [comment]
Hi. Thanky your for helping me out.

Good to hear it should work. On the R2 machine everything starts without exception but all I see is that in the logs there is the one line "programm exiting regulary" (see the main method right at the bottom) and it does not do what the service should do (query data from a database, calculate values and store those back to the db).

1. I published the project from VS2015 to a directory (and started it on my dev machine from there and copied to the R2 machine).  I started it using `NameOfProject.exe action:install`. If I try that with the `NameOfProject.dll action:install` I get an System.IO.FileLoadException that the System.Runtime or one of the dependencies was not found.

2. I am using "PeterKottas.DotNetCore.WindowsService": "1.0.14"
Attaching the project.json below.

3. Well, which version do I have installed... 
My plan was to create a selfcontained service so it would not depend on anything installed on the machine. It's my first .NET/.NET Core project, so I am quite shure I haven't fully understood the concept so far. To understand project.json is a nightmare for a beginner like me.

dev win7 machine:  1.0.0-preview2-1-003177
test S2008R2 machine: 1.0.0-preview2-003156

Interesting point, haven't recognized so far that on the test machine was a different version.

The project.json
`{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.Configuration": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.Json": "1.1.0-preview1-final",
    "Newtonsoft.Json": "9.0.2-beta1",
    "NLog.Web.AspNetCore": "4.3.1",
    "PeterKottas.DotNetCore.WindowsService": "1.0.14",
    "System.IO.FileSystem": "4.3.0"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0" //Optionally add "type": "platform" if you don't want self contained app
        }
      },
      "imports": "dnxcore50"
    }
  },
  "runtimes": {
    "win7-x64": {}
  },
  "publishOptions": {
    "include": [
      "appsettings.json",
      "NLog.config"
    ],
    "exclude": [
      "logs"
    ]
  }
}
`

My Program.cs with the main method looks like this:

`  public class Program
    {

        public const string LOGGER_NAME = "StartUp";

        public static int Main(string[] args)
        {
            try
            {

                ServiceRunner<ExtractMetadataService>.Run(conf =>
                {

                    conf.SetName("Name");
                    conf.SetDisplayName("Displayname");
                    conf.SetDescription("My  Description");

                    conf.Service(serviceConfig =>
                    {
                        serviceConfig.ServiceFactory((extraArguments) => { return new NameOfProjectService();  });

                        serviceConfig.OnStart((service, extraParams) => { service.Start(); });

                        serviceConfig.OnStop(service => {  service.Stop(); });

                        serviceConfig.OnError(e =>
                        {
                            LogManager.GetLogger(LOGGER_NAME).Error(e.GetBaseException(), "serviceConfig.OnError()");
                        });
                    });
                });

             
            }
            catch (Exception e)
            {
                LogManager.GetLogger(LOGGER_NAME).Fatal(e, "program existing with unexpected error");
                return ReturnCode.UNEXPECTED_ERROR;
            }

            LogManager.GetLogger(LOGGER_NAME).Info("programm exiting regulary");

            return 0;
        }

    }
`

**Comment by MontyGvMC** [comment]
a side node: when i start it on R2 without an action as command line tool it works as expected

**Comment by PeterKottas** [comment]
Hey mate, sorry was busy at work so I couldn't reply. Lot of info, that's good :) 
1st of all, it's ok for it to exit after it installs. But it needs to install, you should see logs in the console saying Service bla bla bla has been Successfully installed. And only after that should it continue to "programm exiting regulary". 
2nd you can check the int that Run method returns. It should be 0 if it works, -1 otherwise. It only returns -1 [here](https://github.com/PeterKottas/DotNetCore.WindowsService/blob/master/Source/PeterKottas.DotNetCore.WindowsService/ServiceRunner.cs#L137) therefore if it get's there, you should see the error in the error callback. 
3rd if all fails, let's go medieval on it's ass :D Put a [File.WriteAllText](https://msdn.microsoft.com/en-us/library/ms143375(v=vs.110).aspx) in start, stop and error callback. Write to different files and just check if they are being created. Remember that Start method can actually finish if you don't have a timer, infinite loop or task.Wait somewhere in it. That's intentional by design. 
4th I suggest to make sure the version of sdk matches otherwise who knows what happens :)
5th If you go to services on the test machine, find the installed service and click start/stop, does it remain started?
Bonus: Yep you're right, dot net core definitely has some things you'll need to get used to :) One way to make things easier (IMHO) is download vs 2017 community which contains rc4 in it. That get's rig of project json and things might be more to your liking.

**Comment by MontyGvMC** [comment]
Hi there.

Reporting back with one of those points like "how did that run at the first point anyway". 

The File.WriteAllText did the trick and led me to a series of misunderstandings of the concept an few interessting mistakes I made.

Now the service do not run on my Win 7 dev machine either but this is a problem of my code and not your framework. Your framework works fine now :-)

One tiny thing I haven't figured out is setting the name, displayname and the description. It seems to take always the default name.

`ServiceRunner<ExtractMetadataService>.Run(conf =>
                {

                    conf.SetName("ServiceName");
                    conf.SetDisplayName("ServiceDisplayName");
                    conf.SetDescription("Service description);

                    conf.Service(serviceConfig =>
                    {
                        serviceConfig.ServiceFactory((extraArguments) => {
                     // and so on and on ......

`
But it just takes namespace + class name and "no description"

Any idea what I am doing wrong?

Well, to the missconceptions I had:

1. I used a try catch block in my service which caught and should have logged exceptions. Since I caught them, OnError was never called. Since my logging implementation failed they just disappeared without any hints that an error occured. I removed the try catch and used File.WriteAllText in OnError and tada, there were the hints what was going on

2. I developed and tested from VS as command line tool. I used to load settings from an appsetttings.json and logging configuration from NLog.config . That worked fine as command line tool because the root path was the directory where the exe is and so they looked for rootpath/appsettings.json and found them. When I installed & started it as service the root path became C:\windows\system32 and it raised an error not finding the appsettings.json. (Which than dissappeared due to point 1). The same with NLog.config (which I haven't managed to fix right now).

3. When I set an absolute path to the appsettings.json and removed the (not working) logging the service began to hang never reaching the state "Started". This was because I implemented an endless loop handling my tasks in the service class directly and not in an own thread or using timers. This implementation caused a lot of -1 return codes you mentioned. (Thank you for the hint).

Well, now I have to find a working logging system. Any recommendations what you use for your services?
And then figure out why my service is running in the background (generating log files with File.WriteAll) but not doing the stuff.

Bonus: getting rid of project.json will may not make things easier for me. I come from a Java background. :-) So this is my first .NET project anyway.

**Comment by PeterKottas** [comment]
Morning mate, you've been quite unfortunate with a lot of small things that connected into big hard to figure out mess it seems :) But glad you have some good progress now. Actually, the 3 points you mentioned inspired me to write a "Common problems" section in the read me later on. (If you want, feel free to write it a PR, I would appreciate it a lot ;) )
Now let's resolve what's left there:
Setting name, description and displayName has been simplified thanks to @BigtimeNet before, you had to pass in second optional parameter to force name to change (reason there is it can be provided via parameter and it's kind of hard to decide which one is important :)) Now (if you update to version 1.0.16) it should work right away. This is the [pr](https://github.com/PeterKottas/DotNetCore.WindowsService/pull/11) if you fancied a look.
1. Yep different flavors of this happens to pretty much everyone, that's why it's best to start very very simple. Actually it might be easiest to start from the sample project that is here in the [repo](https://github.com/PeterKottas/DotNetCore.WindowsService/tree/master/Source/PeterKottas.DotNetCore.Example) but you seem to have a good handle on it now.
2. Yep that's very correct. Windows services works this way. Again a good point. The reason why most people won't see it is the proper way to get app path in dot net core is `PlatformServices.Default.Application.ApplicationBasePath` This will work just fine and you obviosuly missed it as you are new to all this.
3. Again, best thing is always to check return and log it (ideally logging should work for that :D)

So now for the logging. A good place to start might be this [article](https://andrewlock.net/using-dependency-injection-in-a-net-core-console-application/). It always makes sense to use DI and the logger they've created for the framework seems to be working nicely. 

They also built the DI, that actually seems to be quite good but obviously you have a choice here as well. Either use that, or maybe autofac or something else. 

Back to logging as that's the number for priority for every app :)
I personally use log4net (I think they have it for java as well so it might be familiar). Works very good but it doesn't play nicely with the dot net core log provider yet. If I was you, I would look into serilog. That works great with log provider and allows for the same fancy stuff like log4net. E.g writing logs into db, rolling appenders and many many more. [This](https://carlos.mendible.com/2016/09/19/step-step-serilog-asp-net-core/) should provide some info about serilog (quite easy to setup). And [the answer here](http://stackoverflow.com/questions/41414796/how-to-get-microsoft-extensions-loggingt-in-console-application-using-serilog) will show you how to do it in console app. 

Good luck, I am pretty sure you'll be done with it very soon.

**Comment by MontyGvMC** [comment]
Hi there.

Thank you for the update and the support.

I managed to get NLog running (needed to make the used loggers static in Program.cs) and fiddled out the remaining issues (missing file access rights, no connectivity to local MS DB but connectivity to the real DB server) and so I have successfully managed to write my first windows service and have it up and running. The polishing is still to do but it does its job for now.

Yeah. Start to like .NET Core too. I wrote a windows service. Never believed that this will ever happen years ago.

As expected it works on Win 7 and Windows Server 2008 R2

Thank you again. Your library is a great thing.

**Comment by PeterKottas** [comment]
Awesome, I am glad I helped to acquire one more soul for the dot net world :D I am sure you'll love it, it's a good framework. Feel free to ask if you have any more issues.

**Comment by gitfortee** [comment]
@MontyGvMC      I need some input. I need to deploy a windows service i built using @PeterKottas  ' library. Now i need some help with deploying the service to a 2008 R2 machine. 

Could you please share if you have used any install scripts to install the service and also how do you do further releases? is it suffice to stop the service using services manager - deploy the new version - and then start the service using services manager ? does it work like that? 

I tried to follow the readme for installation instructions. but I am at the rim of releasing the product and unfortunate to spend time on trying out the the options..

Thanks!

**Comment by PeterKottas** [comment]
First to the second point you made, " is it suffice to stop the service using services manager - deploy the new version - and then start the service using services manager ? does it work like that?"
It's even simpler than that, you just install new version. It will automatically stop, uninstall, install, start for you.

Then first point. I use octopus deploy.Great tool for automating deployments and releases. In general, all you need to automate this some power-shell scripts but I would definitely recommend something like octopus. It's free for use for up to 10 projects I think.

**Comment by gitfortee** [comment]
@PeterKottas thanks for the quick response. I will check this out.

**Comment by gitfortee** [comment]
@PeterKottas can i use the service manager GUI to install this service.? or should i depend on the scripts.? Also, can i use a normal windows user account or should i use only a "service account" ?

**Comment by gitfortee** [comment]
This is the powershell script. 

New-Service -Name "MyServiceName" -BinaryPathName ".\Consoleapp.dll action:run username:domain\username password:passwordstring" -StartupType Automatic 

But i get 

Windows could not start the MyServiceName service on Local Computer.
Error 2: The system cannot find the file specified. 

I looked up the service properties to see the path to executable has ".\Consoleapp.dll action:run username:domain\username password:passwordstring" so how should my powershell command look like.?

**Comment by MontyGvMC** [comment]
Sorry for joining the party that late.

So far the service runs only on a dev environment where it is copied to the target machine via remote desktop and then manually started from the command line.

So can't add anymore than Peter already said.

**Comment by PeterKottas** [comment]
Hey, this is not correct:
`
    New-Service -Name "MyServiceName" -BinaryPathName ".\Consoleapp.dll action:run 
    username:domain\username password:passwordstring" -StartupType Automatic
`
You shouldn't use New-Service as that beats the purpose of this library. If that worked, this lib would be redundant. As it doesn't as you correctly spotted, you should instead do 
`dotnet .\Consoleapp.dll action:run  username:domain\username password:passwordstring`  
Syntax afk but I hope you got the gist
