### ISSUE TITLE
Non-service (i.e., interactive or console) service host quits immediately

### ISSUE THREAD

**Issue by peitschie** [PeterKottas/DotNetCore.WindowsService#30]
Hi! I apologise in advance if I'm mis-understanding the purpose or function of the library, but I am struggling to understand how the interactive/console version of the service runner is intended to function.

Recreating your example service (https://gist.github.com/peitschie/56b95a33cf5822cb598271ddbe54f183), it all runs as desired when installed and run as a Windows service. However, it quits immediately if I run it directly via F5 from within Visual Studio, or even as a console app (e.g., `dotnet NetCoreWindowsService.dll`), only displaying:

```
Service NetCoreWindowsService.Service started
Main exited
```

I had assumed that the intention was it should *not* exit if run via a console, and somehow wait for the service termination to complete. Alternatively, should the `IMicroService.Start` method block when started interactively? If the latter, what's the correct way to read whether the service is RunInteractive, as this property doesn't appear to be exposed via any of the configurations?

Many thanks for this library regardless... even with this small hiccup, this has certainly made it easier for me to get started!

**Comment by PeterKottas** [comment]
Hi there, hope you are well. You got it 99% right, there's just one small nuance that you need to take into consideration. Wind service is a weird beast. It's very straight forward, but the way it works is different than console app. I know there's plenty people who would now how and why but all I need to know is it doesn't work like normal console app. Console app, when it quits main, it just exits the program. Windows service, the "start" method finished there's no real way of it to "wake up" if you will but it still lingers on. 

What I wanted is a behavior close to console app. That's why you are seeing what you are seeing. 

What I do with these microservices normally is I start a task of some sort and then add something like
AFK:
`
#if DEBUG
task.Wait();
#endif
`
Which allows my debugging session to continue but in release I don't care about it as windows service will keep it alive. This might not be the most technical answer but I believe it should be sufficient ;)

**Comment by peitschie** [comment]
After reading through the code, that's pretty much the conclusion that I came to also.

Would you be willing to take patches to improve this a little? E.g., if there was one additional property added to the `IMicroService` interface (e.g., `void WaitForServiceExit`), then the code within the runner could be modified to call that when run in interactive mode.
