### ISSUE TITLE
Can the service run on Linux?

### ISSUE THREAD

**Issue by developer82** [PeterKottas/DotNetCore.WindowsService#6]
Is it possible to run the service as a Linux deamon (service) ?

**Comment by PeterKottas** [comment]
Sorry mate, have to disappoint you on this one. Eventually I might add it (and rename the repo :D ) but that will only happen once I'll have to do it for my project or if I find somebody here who might look into it. That being said, feel free to pick it up and fire away a PR. Otherwise I'll close it for now in a couple of days.

**Comment by xts-velkumars** [comment]
@PeterKottas 

Linux updates?
