### ISSUE TITLE
action::stop Throws NullReferenceException

### ISSUE THREAD

**Issue by markolbert** [PeterKottas/DotNetCore.WindowsService#66]
In running the timer-based example, action:stop stops the service, but the following error message gets printed out on the console:

> > dotnet KottasTest.dll action:stop                                                              
> Successfully stopped service "KottasTest" ("No description")                                     
> Service KottasTest stopped                                                                       
> Service KottasTest errored with exception : Object reference not set to an instance of an object.

I cloned the project down to my development system and linked it into the test project (I did do a nuget update on some packages that were defined in the repository, but which have later versions).

Unfortunately, when I attached the debugger to the service and stepped through the stop action, VS 2017 didn't pick up on any exceptions (I'd set it to break on everything). But the error message still get generated.

I don't have any experience debugging services, but if you have any suggestions on how I might catch where the exception is coming from, I'm happy to try them out.

**Comment by PeterKottas** [comment]
Well this is definitely not so straight forward. Stop should signal to the service via the callback (onStop) that it needs to stop. Therefore clean up all the resources and so on. I wanted to keep the example simple therefore this is not done properly. I assume the exception has something to do with destroying the service while the timer is ticking. You would have to do some extra logging to be sure about that. But frankly, the service should be build in a way when forceful stop (imagine power cut) wouldn't cause a problem. Therefore you might get an exception, even a logged one, but it shouldn't matter much. If for example your service sends emails, it should be synced via a database or queue of some sort so that terminating mid action would result into retry when the service goes back online. Hope it makes sense.

**Comment by markolbert** [comment]
Yes, it does, thanx. It's also why the generation of the exception doesn't cause a problem, so far as I can tell.

BTW, I also tried cloning and linking in the service library your library is based on, thinking the exception might be thrown from somewhere inside of it. No joy.

I also noticed that the exception was being handled through the serviceConfig.OnError() method, but what's interesting is that breakpoints within that lambda method don't get tripped, even though clearly the method is being called. I suspect that's because the error, whatever its source, is being generated late in the tear-down process.

I'll close this issue since it's probably not worth beating it up anymore, since it isn't a showstopper of an issue.

**Comment by ragnarol** [comment]
I know it is closed, but looks like my OnStop handler is being called twice, and the second one the service parameter is null, that is causing the error on my case. A simple check for null fixed it.

Need to investigate why it is called twice though.

**Comment by PeterKottas** [comment]
Definitely strange. I don't remember anybody having problems like this. Wonder if it's environment related maybe (not sure how but still)
