### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by jchannon** [PeterKottas/DotNetCore.WindowsService#7]
Hi,

When you have the below, does `OnStart` / `service.Start` need to block so the console app doesnt just stop after its gone through `ServiceRunner.Run`
```
 public static void Main(string[] args)
        {
            ServiceRunner<MyService>.Run(config =>
            {
                var name = "My Service";
                config.SetName(name.Replace(" ", ""), true);
                config.SetDisplayName(name, true);
                config.SetDescription(name, true);

                config.Service(serviceConfig =>
                {
                    serviceConfig.ServiceFactory((extraArguments) =>
                    {
                        return new MyService();
                    });

                    serviceConfig.OnStart((service, extraArguments) =>
                    {
                        Console.WriteLine("Service {0} started", name);
                        service.Start();
                    });

                    serviceConfig.OnStop(service =>
                    {
                        Console.WriteLine("Service {0} stopped", name);
                        service.Stop();
                    });

                    serviceConfig.OnError(e =>
                    {
                        var location = Path.Combine(Directory.GetCurrentDirectory(), string.Format("{0:yyyy-MM-dd_hh-mm-ss-tt}_vqportal.err", DateTime.Now));
                        var errorString = $"An {e.GetType()} exception has occured: {Environment.NewLine}\t{e.Message}{Environment.NewLine}\t{e.StackTrace}";
                        Console.WriteLine(errorString);
                        File.WriteAllText(location, errorString);
                    });
                });
            }); 
        }
```

**Comment by PeterKottas** [comment]
Hi @jchannon, it's pretty easy to verify. Just add some logging into file and see what happens ;) To save you the trouble. The "start" and "stop" here are windows things. So the service is in fact kept alive unless the stop is explicitly called. Windows services in general are apps that are expected to run as a service therefore for a long time. I would assume there would be some infinity loop or timer hidden somewhere in order for it to make sense. All depends on what you are trying to achieve. But if you run this interactively, it will behave like a console app and quit immediately after it's done executing the code.

**Comment by dasMulli** [comment]
In case this runs as windows service, it actually is just blocking on a Task [here](https://github.com/dasMulli/dotnet-win32-service/blob/master/src/DasMulli.Win32.ServiceUtils/Win32ServiceHost.cs#L104). It's a bit different than how `ServiceBase` works (which bugged my in the past).

**Comment by PeterKottas** [comment]
Ah I see, but I assume that doesn't change the fact that the service won't stop. Or does it? The way I see it the service will remain seemingly alive awaiting stop command. Or would it stop after execution and call stop callback by itself?

**Comment by dasMulli** [comment]
Sry, didn't read.
When run as windows service, `Win32ServiceHost.Run()` will block until the service transitions to "stopped", which happens when a stop command has been processed correctly or the service calls the "stopped callback delegate" passed to it in the start method of the `IWin32Service` implementation.
I don't know how you (@PeterKottas) abstracted it when running in "interactive mode" (console), If you support that - but then you'd need to implement blocking yourself.
Btw, I'll soon be obsoleting/removing the `RunAsync()` method because there may be issues when it is not run from the main thread and on how the underlying method blocks in these situations... Guidance will be to call `.Run()` on the main thread and expect it to block until the service shuts down.

To clarify for anyone who reads this: I'm talking about a package layer below @PeterKottas nice API, a small wrapper around the native win32 API methods.

**Comment by PeterKottas** [comment]
Sure np was just cleaning up mate :) Interactive here is pretty much ignoring the service layer and running the start method of the service directly so all good there. Good to know about the blocking, that clears things up. I  am using the Run method [here](https://github.com/PeterKottas/DotNetCore.WindowsService/blob/master/Source/PeterKottas.DotNetCore.WindowsService/ServiceRunner.cs#L293) so no probs about the RunAsync. Yep this is a talk about the internals, if anybody is interested I definitely recommend to check out @dasMulli s lib.
