### ISSUE TITLE
Console.SetTitle leads to error "The service did not respond to the start or control request in a timely fashion"

### ISSUE THREAD

**Issue by bjorn-greenchoice** [PeterKottas/DotNetCore.WindowsService#77]
In a .NET Core 2 Console application, if you set the console title (`Console.Title = "SomeTitle"`;) in the main method of your app, the service refuses to start.

The error message is "The service did not respond to the start or control request in a timely fashion"

Action:Install also fails, in the sense that it does install the service, but does not start, with the same message.

Other interactions with the console (like console.writeline) do not appear to cause any problem.

**How to reproduce:**
- Create a new project (`dotnet new mcrsvc-min`)
- Build and publish the resulting project to an executable (`dotnet publish -r win10-x64`)
- Install the executable as a service (`MyTestService.exe action:install`) - works fine
- Uninstall the service again
- Modify Program.cs to include `Console.Title = 'MyTitle';` as the first statement in the Main method.
- Build and publish
- Install the executable as a service again (error occurs)
- Attempt to start the service using services.msc (same error)

**Comment by PeterKottas** [comment]
That sounds like a problem on your end. I have been using on many of my services with no problems. 
"The service did not respond to the start or control request in a timely fashion" usually means an exception in service or that you have to run as admin. Worst case clone the lib and try it directly.

**Comment by avisonmaher** [comment]
I can second this. 

My microservice has been working fine for months, but for some reason in the last week or so (since I updated to 2.0.6) I have been getting the "The service did not respond to the start or control request in a timely fashion" and I would never have thought it was due to setting the title on the console until I found this issue.

**Comment by bjorn-greenchoice** [comment]
Eventually we ended up working around the problem. The error, in our case, is specific to the `Console.Title = "MyTitle";`. If we don't set the console title,  everything works. So we ended up simply not setting the console title.

**Comment by PeterKottas** [comment]
It sounds very strange that it would fall over just because of this. However, what I would suggest is maybe surround the set title in #IF DEBUG statement. As I would expect this is only used for debugging. I'll do some investigation later on but I don't have time to do it now as this is fairly minor issue that doesn't affect functionality.
